- arango/api.py
- arango/clients/base.py
- arango/clients/session.py
- arango/tests/test_index.py
- docs/arango.clients.rst
The session based client is faster than the default one, especially at high rates. It's no longer paying the connection and breakdown penalty per socket and instead is connection pooling, which is great since the current DefaultArangoAgent was creating a new connection per document sent.
There are two tests, the geo tests. They don't return back the unique flag that you send in, I suspect that that index type does not support unique. However, I'm new to arangodb, so I don't know perhaps it's a bug in the server I'm running 2.5.5. I also added the sparse and selectivity keys where needed. I'm not sure if this breaks backwards compat with older servers, I'm sorry if it does, I just didn't want to hand back a broken test suite especially since you went through the trouble to build one.
> Pull request to address one connection per send on DefaultClient

- README.md
- arango/database.py
- arango/tests/test_transaction.py
Really appreciate the effort going into this driver -- just looking to add params to transactions. As far as I can tell this doesn't break compat with older versions, but I only tested on 2.5 (ran nosetests with new test case).
> Adding params to execute_transaction

- docs/index.rst
As dicussed at https://github.com/joowani/python-arango/issues/50, I've edited the index page to reflect changes on the documentation about thread safety of the driver.
> Update index.rst to point on thread safety

- .gitignore
- arango/api.py
- arango/aql.py
- arango/client.py
- arango/collections/base.py
- arango/collections/edge.py
- arango/collections/standard.py
- arango/collections/vertex.py
- arango/database.py
- arango/graph.py
- scripts/setup_arangodb_mac.sh
Hello,
I was working with your library and noticed that you were implementing the connection passthrough using a monkey patch to __getattribute__.  This makes it quite difficult to determine where in the code the function calls to connection.handle_request were occuring.  I have refactored it to deal with this in a better manner, using a base class with a handle_request method.
Secondly, I made two changes, one in client and one in database, where they were failing on a key error in python 3.  I have replaced these to use what I believe to be an equivalent syntax.
Third, I have added a setup_arango_mac.sh script.
Lastly, this appears to fail 3 tests for permissions management reasons.
In test_user line 228, it appears nonexistent users access checking now throws …
> Remove API method monkey patching

- arango/batch.py
- arango/database.py
- arango/lock.py
- tests/test_batch.py
Simple, blocking implementation of BatchExecution.  This implementation uses locks to manage write control over the object.  However, the lock implementation in python 2 does not have a timeout option.  Therefore, one had to be created for python 2 based on Queue.Queue.  In python 3, threading.Lock is used.
> Add changes to make BatchExecution thread safe

- arango/api.py
- arango/connections/async.py
- arango/connections/base.py
- arango/connections/batch.py
- arango/connections/cluster.py
- arango/connections/transaction.py
- arango/exceptions/base.py
- arango/http_clients/base.py
- arango/http_clients/default.py
- arango/jobs/base.py
- arango/jobs/batch.py
- arango/jobs/sync.py
- arango/responses/__init__.py
- arango/responses/base.py
- arango/responses/lazy.py
- setup.py
This submission cleans up the job kwargs concept by removing it entirely.  Scanning the entire codebase again, I was able to replace most of it with a single call to functools.partial
> Submission that removes kwargs structure

- arango/executor.py
- tests/test_transaction.py
In my application, I saw an error where a transaction containing only AQL would fail because the write collections were not declared. I traced this to the `read` and `write` parameters to `begin_transaction` not being passed all the way through to the database in `commit`.
> Honor read and write params to begin_transaction

- arango/cursor.py
The `'_count'` slot was already defined on line 35.
> Remove duplicate '_count' slot from Cursor

- arango/formatter.py
- tests/test_view.py
When retrieving a view property the `links` attribute is a dict and not a list.
The key is the collection name and the value the link attributes.
> Fixes view links format

- arango/aql.py
- arango/collection.py
- arango/database.py
- arango/exceptions.py
- arango/executor.py
- arango/formatter.py
- arango/replication.py
- arango/wal.py
- docs/collection.rst
- tests/test_collection.py
- tests/test_database.py
- tests/test_replication.py
- https://www.arangodb.com/docs/3.7/appendix-deprecated.html
- For some of these I compared the 3.6 and 3.7 docs for API endpoints: https://www.arangodb.com/docs/stable/http/collection-creating.html
> Remove MMFiles references and exclusive options

- arango/collection.py
Although not entirely clear from this documentation: https://www.arangodb.com/docs/3.7/data-modeling-collections-collection-methods.html#properties
This page indicates it should be possible to set the schema property for existing collections: https://www.arangodb.com/docs/3.7/data-modeling-documents-schema-validation.html
> Allow configuring schema property for existing collections

- docs/simple.rst
Just saw you added this - really nice listing - and useful when you can use them.
I started using them and then had to back out as they aren't dependable. I didn't realize how limited they were.
Your library and docs just keep getting better and better. Thank you!
> Warning about simple queries

- arango/database.py
SmartGraphs needs a "smartGraphAttribute" to be defined. 
Additionally, this needs to be set inside the options object `{options: {smartGraphAttribute: <attribute>}}`.
Same for `numberOfShards`.
> fix smart graph creation

- arango/aql.py
Allow to provide bind_vars as parameter for `explain` and pass it to the request.
> [Fix] Explaining a query with bindings requires bindVars to be set.

- arango/client.py
- arango/connection.py
- arango/resolver.py
- tests/test_resolver.py
Closes #179 
A (working) first-draft implementation for host fallback support.
Requires feedback
What's new:
* `BaseConnection.process_request()`
* Given a request, process it until a valid response is provided, or the max amount of tries has been reached.
* `host_index` is still being chosen using the resolver's `get_host_index` method.
* `HostResolver.max_tries : int`
* A limit to the amount of attempts made to execute the request. Value varies based on the resolver type
* `HostResolver.host_count : int`
* The number of hosts provided
* `RandomHostResolver.get_host_index()`
* Reworked to keep track of previously chosen host indexes, to make sure that the next chosen host_index is not one of them.
> feature: host fallback support

- arango/connection.py
From a discussion with the ArangoDB Java & Go maintainers (cc @rashtao):
> please note that failover/retry in case of status 503 should happen only in these cases:
1. the response has body like {"error":true,"errorNum":503,"code":503, ...}, note errorNum=503
2. the 503 response comes from an intermediate proxy, so it does not contain a json body like the one above
Other 503 responses  with different errorNum should not lead to failover/retry, but just thrown to the caller.
> new: fallback host support for 503 errorNum

- arango/client.py
- docs/certificates.rst
- docs/http.rst
- tests/test_client.py
This PR allows overriding the TLS verification behavior.
It defaults to None and thus will have no effect if not explicitly defined.
If it is defined, it allows for enabling/disabling verification and defines a custom CA bundle file or directory as specified by the [requests](https://docs.python-requests.org/en/master/user/advanced/#ssl-cert-verification) library.
Fixes #201
> [Fix] Make overriding TLS verification optional

- arango/collection.py
- arango/database.py
- arango/utils.py
- tests/test_document.py
- tests/test_graph.py
Introduces batch insertion via the `import_bulk` API.
These changes warrant a minor version increment.
```py
vertices = [{'foo': str(i)} for i in range(1, 101)]
db.create_collection('numbers')
results = db.collection('numbers').import_bulk(vertices, batch_size=len(vertices)//10)
assert len(results) == 10
```
> Add batch_size parameter in import_bulk method

- arango/collection.py
- tests/test_document.py
Now that `batch_size` has been introduced to `import_bulk()`, we should be checking that users don't use both the `overwrite` and the `batch_size` parameters in the same call.
If server-side batching is ever introduced to `/_api/import`, then this restriction could most likely be lifted.
Warrants a 7.4.1 release
> Prevent batch_size parameter usage when overwrite is set to True in bulk_import  

- arango/collection.py
- tests/test_document.py
Add overwrite_mode, keep_none, merge similar to insert method.
They were added in arangodb 3.7
> Add missing parameters to insert_many method

- arango/client.py
- tests/test_client.py
- Added `request_timeout` property to `ArangoClient` to overwrite `DefaultHTTPClient.REQUEST_TIMEOUT`
- Added `request_timeout` constructor parameter in `ArangoClient` to initialize `request_timeout` property. The default value for this parameter is -1. Any other value supplied, including `None` will overwrite `DefaultHTTPClient.REQUEST_TIMEOUT` 
- Added `# type: ignore` to lines 141 and 146 because they failed `mypy`. However, they work perfectly well when tested. Any suggestions here is very much appreciated.
> Add 'read_timeout' option in client.py

- arango/collection.py
- arango/formatter.py
Implemented the following changes:
1) New JSON fields: storedValues and cacheEnabled (https://github.com/arangodb/docs/blob/main/3.10/release-notes-api-changes310.md#index-api)
2) New JSON field: legacyPolygons (https://github.com/arangodb/docs/blob/main/3.10/indexing-geo.md#legacy-polygons
https://github.com/arangodb/docs/blob/main/3.10/release-notes-new-features310.md#geojson-changes)
3) Deprecate fulltext index 
(https://github.com/arangodb/docs/blob/main/3.10/release-notes-upgrading-changes310.md#indexes)
@joowani, we would like to discuss and implement a proper deprecation convention.
> 3.10: Implemented changes to the Index API

- arango/aql.py
- arango/exceptions.py
- arango/formatter.py
Added support for the GET /_api/query/rules endpoint that returns the available optimizer rules for AQL queries.
https://github.com/arangodb/docs/blob/main/3.10/release-notes-api-changes310.md#optimizer-rules-for-aql-queries
> 3.10: Implemented query rules endpoint

- arango/database.py
- arango/formatter.py
Added computedValues property to collection
https://github.com/arangodb/docs/blob/main/3.10/data-modeling-documents-computed-values.md
> 3.10: Added computedValues

- arango/formatter.py
- arango/pregel.py
- Added support to retrieve all running jobs 
https://www.arangodb.com/docs/devel/http/pregel.html#get-currently-running-pregel-jobs
- Added the new `details` JSON element in 3.10
https://github.com/arangodb/docs/blob/main/3.10/release-notes-api-changes310.md#pregel-api
> 3:10 Updated Pregel API Features

- arango/aql.py
- arango/collection.py
- arango/database.py
- arango/executor.py
Added `allow_dirty_read` optional parameter to methods for the following:
- Single document reads (`GET /_api/document`)
- Batch document reads (`PUT /_api/document?onlyget=true`)
- Read-only AQL queries (`POST /_api/cursor`)
- The edge API (`GET /_api/edges`)
- Read-only Stream Transactions and their sub-operations (`POST /_api/transaction/begin etc.`)
https://github.com/arangodb/docs/blob/main/3.10/release-notes-api-changes310.md#read-from-followers
> 3.10: Read from Followers (allow dirty read)

- arango/formatter.py
If `computedValues` is `None` it can not be iterated over.
Fixes #223
> Only set computedValues if value exists and is not None

- arango/collection.py
When updating to ArangoDB 3.10, the driver is no longer able to create persistent indexes.
Error:
```
arango.exceptions.IndexCreateError: [HTTP 400][ERR 10] invalid number of index attributes
```
The value for storedValues is set to an empty list by default which yields an error. 
Instead it should be unset by default.
Plus:
I also realised that the parameters do not adhere to the naming convention in the library.
The parameter should be named `stored_values` instead of `storedValues` (same goes for `cacheEnabled`).
I left the name, but can also fix this as part of this PR if you want me to do this.
Reference: someengineering/resoto#1294
> [fix] Persistent index creation fails.

- arango/request.py
This is necessary to remove the docs errors while we find a solution for driver version.
> Removed reference to arango.version in request.py

- arango/formatter.py
3.9+ returns a different JSON structure from 3.10. So, `format_view()` is simply copying across the `links` property.
> Fixed format_view link properties

- MANIFEST.in
- setup.py
Closes #203
1. `pip install mypy git+https://github.com/ArangoDB-Community/python-arango.git@fix/mypy-py-typed`
2. `echo "from arango.database import StandardDatabase" >> temp.py`
3. `mypy temp.py`
> Add PEP 561 guideline

- .github/workflows/build.yaml
- .gitignore
- CONTRIBUTING.md
- arango/backup.py
- arango/collection.py
- arango/formatter.py
- docs/foxx.rst
- tester.sh
- tests/conftest.py
- tests/static/cluster.conf
- tests/static/single.conf
- tests/test_backup.py
- tests/test_collection.py
- tests/test_document.py
- tests/test_foxx.py
- tests/test_replication.py
- tests/test_user.py
Currently, the `main` branch is only tested against ArangoDB 3.7 single-server.
This PR bumps that version to 3.10.6. Due to that, additional changes were needed:
- make sure newly (since 3.7) are available
- adapt unit tests (some were broken from before, some became broken due to newer ArangoDB versions)
- decide the officially supported Python versions (we're going to support the default Python versions that come with the last two Ubuntu LTS releases)
Apart from bumping the ArangoDB version to 3.10.6, the CI will stay the same, until we decide regarding the _CircleCI_ integration. Until then, I am using the `tester.sh` script locally for running more comprehensive suites. I ran **everything** against 3.9.10 and 3.10.6. Rest assured, this is not going to stay like that. I will push for …
> [DE-593] Support latest ArangoDB version

- arango/client.py
- setup.py
- tests/test_client.py
Copying description from [issue](https://github.com/ArangoDB-Community/python-arango/issues/249):
`pkg_resources` is now deprecated in favor of `importlib.metadata` / `importlib_metadata` ([source](https://setuptools.pypa.io/en/latest/pkg_resources.html)). Right now it causes warnings and in the future (3.12?) I think it will stop working entirely. I saw there was a related [pr](https://github.com/ArangoDB-Community/python-arango/pull/233) but it was using `importlib.metadata` which apparently has different behaviors on some versions of python and caused issues for some users ([ref](https://github.com/ArangoDB-Community/python-arango/issues/244)). Maybe it would be acceptable to use `importlib_metadata` (the backport) either on all versions of python or only when necessary.
> Replace pkg_resources with importlib_metadata

- CHANGELOG.md
- arango/aql.py
- arango/formatter.py
- arango/request.py
- setup.py
- tester.sh
- tests/conftest.py
- tests/test_aql.py
**Purpose**
Enhance the AQL `explain` functionality by adding the following attributes (available since 3.10.4):
- peakMemoryUsage (number): The maximum memory usage of the query during explain (in bytes)
- executionTime (number): The (wall-clock) time in seconds needed to explain the query.
Note that the explain method of AQL queries includes the "stats" field in the returned object. The REST API returns it separately from the "plan" field, but for now we have to merge them together to ensure backward compatibility.
**Additionally, the following changes are being made**
- Adding peak_memory_usage as a new property of AQL queries, available since ArangoDB 3.11
- Adding a CHANGELOG file for keeping track of changes across driver releases
**Tests**
The necessary tests have been adapted. …
> [DE-546] Adding stats fields to the explain API

- CHANGELOG.md
- arango/database.py
- arango/formatter.py
- tests/test_database.py
Hello  @joowani @apetenchea !
I decided to create this PR because I really need this changes for my Benchmarks project. Here is the short description of changes:
- Added 'details' boolean parameter for getting more detailed version description: `/_db/_system/_api/version?details=true`
- Remove only service fields from view definitions. It will help us in future when new features will be added. I think we should do the same thing for every DDL objects
What do you think about this PR?
> Improvements

- .github/workflows/build.yaml
- CHANGELOG.md
- arango/aql.py
- arango/cursor.py
- docs/cursor.rst
- tester.sh
- tests/test_cursor.py
**Purpose**
Added `allow_retry` query parameter, making it possible to retry fetching the latest batch from a cursor. This corresponds to the [allowRetry](https://www.arangodb.com/docs/3.11/http/aql-query.html#execute-aql-queries) parameter from the REST API.
In case the latest `fetch` failed, `cursor.retry()` yields the latest batch that is cached. Note that if `fetch` succeeds, `retry` works just the same as a normal `fetch`, yielding the next batch.
**Tests**
Two new cursor tests have been added.
> [DE-544] Retriable batch reads

- arango/aql.py
- arango/cursor.py
- docs/cursor.rst
- tests/test_cursor.py
This PR is a follow-up to https://github.com/ArangoDB-Community/python-arango/pull/254
Instead of having a separate `retry` function, it becomes the default behavior of the cursor to always fetch the last batch (that is, only if the `allow_retry` option is specified in the AQL query).
This adjustment reduces the complexity of the API and makes it easier to use. Also, users may start benefiting directly from this change after upgrading to 3.11, without having to make any refactoring to their existing code. All that is needed now is to set `allow_retry=True` in `arango.aql.AQL.execute`
I have added a code block to the documentation to illustrate the usage.
> [DE-544] Adjusting allowRetry implementation

- arango/client.py
- arango/http.py
- tests/test_client.py
This PR makes the `DefaultHTTPClient` more flexible, adding the following new parameters:
- request_timeout: socket timeout in seconds for each individual connection
- pool_connections: the number of urllib3 connection pools to cache
- pool_maxsize: the maximum number of connections to save in the pool
- pool_timeout: if set, then the pool will be set to block=True, and requests will block for pool_timeout seconds and raise `EmptyPoolError` if no connection is available within the time period
The ones prefixed with *_pool* are all passed to the `PoolManager`. Note that these values cannot be changed once the HTTP client has been created.
The following constants were already used before, but are now configurable as parameters:
- request_timeout 
- retry_attempts
- backoff_factor
Note that …
> [BTS-1515] Pass PoolTimeout as argument

- CHANGELOG.md
- arango/collection.py
- arango/formatter.py
- tests/test_index.py
- tests/test_view.py
A couple of inverted index parameters were introduced in 3.10.2 (enterprise only):
- cache: Always cache the field normalization values in memory for all fields by default.
- primaryKeyCache: Always cache the primary key column in memory.
This PR adds them as parameters to `Collection.add_inverted_index` and adds a relevant unit test for inverted index creation.
Additionally, a views test has been enhanced.
> [DE-558] ArangoSearch column cache

- CHANGELOG.md
- arango/collection.py
- tests/test_document.py
Adding new per-operation option `refillIndexCache` to write operations:
- single-document write operations (insert, replace, update, delete)
- multi-document write operations (insert_many, replace_many, update_many, delete_many)
If the option is set to `True`, new entries are added to in-memory index caches if
document operations affect the edge index or cache-enabled persistent indexes. Every
currently running transaction will keep track of which in-memory index cache entries
were invalidated by the transaction, and will try to (re-)fill them later.
Example:
```python
collection.insert({"foo": "bar"}, refillIndexCaches=True)
db.aql.execute("INSERT {foo: bar} INTO collection OPTIONS { refillIndexCaches: true }")
```
> [DE-562] Index Cache Refilling

- tests/static/cluster.conf
- tests/static/single.conf
- tests/test_collection.py
- tests/test_database.py
It is the responsibility of the server to enable extended names. The driver can send any UTF-8 string along with the request.
Therefore, this PR doesn't really add any new and exciting features. Instead, it adds two tests (one for databases and one for collections), making sure the driver can successfully forward UTF-8 names to the server.
Note that, in order to run the tests, the server has to be started with the `--database.extended-names` option. Unfortunately, this is only possible starting with 3.11 docker images, and we're currently using 3.10.9 for our GitHub actions. Nevertheless, I have added the parameter as a comment for now. I can confirm the tests have passed locally for versions >= 3.11.0.
> [DE-545] UTF-8 names

- tests/test_analyzer.py
DE-566 seeks to introduce `geo_s2` analyzer creation support.
Given that the `database.create_analyzer` method accepts `analyzer_type` as a parameter, there is no feature implementation required.
Nevertheless a test case has been added to ensure `python-arango`'s support for `geo_s2` analyzer creation (on EE >=3.10.5 only)
> [DE-566] geo_s2 analyzer test case

- arango/client.py
- arango/http.py
- tests/test_client.py
This PR allows a python-arango `ArangoClient` to be serialized and deserialized correctly using `pickle`. This is needed for usage in multi-process environments. 
To solve this, two named functions replace the `lambda` functions for JSON serialization and deserialization in the client constructor, and the `DefaultHTTPAdapter` now correctly overrides its `__attrs__` variable, including the latest timeout variables to support correct `__getstate__` and `__setstate__` calls.
> Fix python-arango Client (de)serialization

- arango/collection.py
- tests/test_document.py
New `raise_on_document_error` parameter for `update_many`: 
```
:param raise_on_document_error: Whether to raise if a DocumentRevisionError
or a DocumentUpdateError is encountered on an individual document,
as opposed to returning the error as an object in the result list.
Defaults to False.
```
```py
col.update_many(docs, raise_on_document_error=True)
```
> new: `raise_on_document_error` param for `collection.update_many`

- CHANGELOG.md
- arango/collection.py
- arango/exceptions.py
- arango/request.py
- tester.sh
- tests/test_collection.py
- tests/test_database.py
**Main changes**
- Adding `shards()` method to `Collection`, reflecting [/_api/collection/{collection-name}/shards](https://www.arangodb.com/docs/stable/http/collection.html#get-the-shard-ids-of-a-collection). It will be available only in a cluster setup.
**Minor patches**
- Adding docstring for `computed_values`
- Updating driver version in request header
- Fixing `test_database_misc_methods`. Getting and setting log levels for individual servers is available only in a cluster.
> [DE-542] Adding support for shards retrieval

- CHANGELOG.md
- arango/collection.py
- arango/exceptions.py
- arango/utils.py
- tests/test_document.py
- tests/test_index.py
**Main changes**
- Re-implements the following methods via AQL:
- `collection.ids`
-  `collection.keys`
-  `collection.all`
-  `collection.find`
-  `collection.find_in_box` (requesting feedback / second opinion on implementation)
-  `collection.random`
-  `collection.update_match`
-  `collection.replace_match`
-  `collection.delete_match`
- Implements the `collection.get_index` method (`GET /_api/index/{id}`) as it was previously missing
**Miscellaneous changes**
- New utility function: `build_filter_conditions` (now used in the filter-based simple methods)
- Add `allow_dirty_read` parameter to the reworked simple methods given that they are now implemented using the `_api/cursor` endpoint
- docstring cleanup
- test case cleanup
> [DE-584] Refactor Deprecated `/_api/simple` methods 

- arango/utils.py
- tests/test_document.py
The current implementation of `arango.utils.build_filter_conditions()` does not support filtering by `None` values (see the [test failures ](https://github.com/ArangoDB-Community/python-arango/actions/runs/6029808907/job/16360196835?pr=277)triggered by [75d7d7a](https://github.com/ArangoDB-Community/python-arango/pull/277/commits/75d7d7ab97151a996d80a7b8fe812d2ebbefe2cd))
This method is being used across many of the "simple" methods as of #275 
A simple fix is to rely on `json.dumps` to serialize the arbitrary values into a JSON formatted string
> fix: `build_filter_conditions` utils method

- arango/database.py
- tests/test_view.py
- Introduces `view_info()` to retrieve basic information about a View. Not to be confused with the existing `view()` method, which returns the entire properties of a View
> [DE-668]: `GET /_api/view/{view_name}`

- arango/database.py
- tests/test_database.py
- Introduces `databases_accesible_to_user()` to return the list of databases currently accessible to the user
> [DE-670]: `GET /_api/database/user`

- arango/database.py
- arango/exceptions.py
- Introduces `shutdown_progress` to query the progress of _soft_ shutdown 
- Introduces the `soft` parameter to the `shutdown` method to support soft shutdowns
> [DE-672] `GET /_admin/shutdown`

- arango/collection.py
- arango/exceptions.py
- tests/test_collection.py
* introduces `info()` to fetch some information about a collection
* introduces `compact()` to run a compact operation
> [DE-667]: `GET /_api/collection/{name}` & `PUT /_api/collection/{name}/compact`

- CHANGELOG.md
- arango/database.py
- arango/executor.py
- arango/formatter.py
- arango/job.py
- arango/request.py
- docs/batch.rst
- tests/helpers.py
- tests/test_batch.py
https://www.arangodb.com/docs/stable/http/batch-request.html
- The batch API is deprecated since ArangoDB 3.8.0 and will be removed in a future version.
- The `BatchDatabase` is still available, but it now uses a `TreadPoolExecutor` internally.
- For backwards compatibility, the `BatchDatabase` uses only one worker thread, essentially sending the requests sequentially. Feel free to set the `max_workers` parameter to a higher value if you want to use multiple threads, but be aware that the requests will be sent in parallel, which may cause problems if you are using transactions.
- To discourage the use of this API, we now issue a warning when the `BatchDatabase` is used. This warning may be disabled by the user.
Note that `{"foo": "bar"}` may be inserted after `{"foo": "baz"}` in the …
> [DE-664] Deprecating Batch API

- arango/database.py
- arango/exceptions.py
- tests/test_database.py
* Introduces `license()` and `set_license()` to get & set the license of an ArangoDB EE Instance
> [DE-671]: `GET + PUT /_api/admin/license`

- arango/cluster.py
- arango/exceptions.py
- docs/cluster.rst
- tests/test_cluster.py
This PR adds the following functionality to the `Cluster` class:
- **calculate_imbalance** (GET /_admin/cluster/rebalance) - used for getting the current cluster imbalance
- **rebalance** (PUT /_admin/cluster/rebalance) - used for rebalancing the shard distribution (calculates and then executes a rebalancing plan)
- **calculate_rebalance_plan** (POST /_admin/cluster/rebalance) - calculates (but does not execute) a rebalancing plan
- **execute_rebalancing_plan** (POST /_admin/cluster/rebalance/execute) - executes an already calculated rebalancing plan
A small documentation example has been added, together with the unit tests.
For reference, see the [Rebalancing Section](https://www.arangodb.com/docs/stable/http/cluster.html#rebalance) of the official documentation.
> [DE-666] Cluster Rebalance

- arango/database.py
- arango/exceptions.py
- tests/test_transaction.py
- Introduces `list_transactions()` to list the running stream transactions
> [DE-665]: `GET /_api/transaction`

- arango/graph.py
- tests/test_graph.py
It was previously stated that the `graph.vertex_collections()` method excluded orphan collections, which is not/no longer the case
not sure when this has changed however
> Fix `graph.vertex_collections` docstring

- arango/client.py
- arango/connection.py
- arango/exceptions.py
- docs/auth.rst
- tests/test_auth.py
Closes #238 
Introduces a `user_token` parameter to the `arango.client.ArangoClient.db` method to build a `JwtConnection` object without a `username/password` and without `auth_method="jwt"`
also introduces `set_token` to `arango.connection.JwtConnection` and `arango.connection.JwtSuperuserConnection`
```py
import os
from arango import ArangoClient
token = os.environ["ARANGODB_USER_JWT"]
db = ArangoClient().db(user_token=token)
db = ArangoClient().db(username=..., password=..., user_token=token) # Valid, but ignores `username` and `password` params
db.conn.set_token(token=...) # Valid
db.conn.refresh_token() # Raises `arango.exceptions.JWTRefreshError`, since `username/password` is not set
ArangoClient().db(user_token=expired_token) # Raises `JWTExpiredError`
```
> Authenticate using User JWT-Token

- arango/utils.py
- tests/test_document.py
Closes #295 
Warrants a `7.8.1` release
> hotfix: build_filter_conditions

- arango/database.py
- tests/test_database.py
- announcing deprecation of `arango.database.Database.read_log`
- new `arango.database.Database.read_log_entries` method
> DE-699 | Update global server logs retrieval

- README.md
Looking for a second opinion on this new set of readme badges
Copying the same layout we use for the adapters (e.g [NetworkX Adapter](https://github.com/arangoml/networkx-adapter#readme))
Happy to adjust!
[Current Badges](https://github.com/ArangoDB-Community/python-arango#readme)
[Proposed Badges](https://github.com/ArangoDB-Community/python-arango/tree/new-readme-badges#readme)
> Optional: Update Readme Badges

- arango/aql.py
- tests/test_aql.py
Similar to https://github.com/arangodb/arangodb-java-driver/pull/491, introduces the `forceOneShardAttributeValue` parameter to the AQL Query Options
> ES-1867 | `force_one_shard_attribute_value` param

- docs/simple.rst
No longer relevant after https://github.com/ArangoDB-Community/python-arango/pull/275
> remove `simple.rst` warning

- docs/index.rst
Grouping similar `rst` files together, happy to accept feedback
[Before](https://docs.python-arango.com/en/main/#contents)
After:
> re-structure `Contents` in `index.rst`

- arango/collection.py
- arango/formatter.py
- tests/conftest.py
- tests/test_index.py
Internal discussions have established that an `mdi` index is an alias for a `zkd` index, similar to the `hash` index & `persistent` index situation.
Given that python-arango never had support for `zkd` index creation, this PR introduces both `add_zkd_index` and `add_mdi_index`
i.e
- MDI (>=3.12)
- ZKD (<3.12)
Ref: https://docs.arangodb.com/3.12/index-and-search/indexing/working-with-indexes/multi-dimensional-indexes/
Happy to address this in another way, perhaps there's no need for 2 methods?
> DE-743 | MDI/ZKD Indexes

- arango/database.py
> Since ArangoDB 3.8, there have been two APIs for retrieving the metrics in two different formats: /_admin/metrics and /_admin/metrics/v2. The metrics API v1 (/_admin/metrics) was deprecated in 3.8 and the usage of /_admin/metrics/v2 was encouraged.
> In ArangoDB 3.10, /_admin/metrics and /_admin/metrics/v2 now behave identically and return the same output in a fully Prometheus-compatible format. The old metrics format is not available anymore.
Ref: https://docs.arangodb.com/3.11/release-notes/version-3.10/api-changes-in-3-10/#endpoint-return-value-changes
> update `/metrics` endpoint to `v2`

- arango/collection.py
- tests/test_index.py
Closes https://github.com/ArangoDB-Community/python-arango/issues/234
Not sure how else to handle this
We are currently using the parameter name `ordered` to specify whether a Geo Index should be created using GeoJson data-format or not, which can be confusing to users.
This PR just renames the parameter to `geo_json`
Ref: https://docs.arangodb.com/3.11/index-and-search/indexing/working-with-indexes/geo-spatial-indexes/
> breaking: fix `geoJson` parameter

- docs/pregel.rst
- tests/test_pregel.py
This PR disables the Pregel tests for newer ArangoDB versions and updates the docs such that users would be aware why the API doesn't work on 3.12+.
> Pregel is deprecated starting from 3.12

- README.md
- docs/contributing.rst
- pyproject.toml
Moving this repo from `github.com/ArangoDB-Community` to `github.com/arangodb`
> update organization to `arangodb`

- arango/collection.py
- tests/test_document.py
This PR adds support for External versioning which is introduced in 3.12: https://github.com/arangodb/arangodb/pull/20382
https://arangodb.atlassian.net/browse/ES-1771?atlOrigin=eyJpIjoiMzM4NDI1MDkxMzBlNDA2MjhkZjUyOGI2NDc3NmJlNzIiLCJwIjoiamlyYS1zbGFjay1pbnQifQ
https://arangodb.atlassian.net/browse/ES-1771
> [3.12]: External versioning support

- arango/client.py
- arango/collection.py
- arango/connection.py
- arango/http.py
- docs/compression.rst
- docs/index.rst
- docs/specs.rst
- tests/test_client.py
Adding compression of requests and responses, as implemented in https://github.com/arangodb/arangodb/pull/20128
By default compression is turned off, so this change has no effect unless the user specifies one of the newly introduced parameters.
The `ArangoClient` gets two optional parameters:
- `request_compression` - Represents the compression strategy, `None` by default. The reason for passing in an object instead of a string (such as *deflate*) is to allow the client to fine tune the compression algorithm.
- `response_compression` - The equivalent of an `Accept-Encoding` string. This has no effect unless the server is configured to use encoding.
```python
client = ArangoClient(
hosts="http://127.0.0.1:8529",
request_compression=DeflateRequestCompression(), …
```
> [DE-716] Compression of requests and responses

- .circleci/config.yml
- README.md
- docs/index.rst
- tests/test_analyzer.py
- tests/test_aql.py
- tests/test_cluster.py
- tests/test_collection.py
- tests/test_cursor.py
- tests/test_database.py
- tests/test_index.py
- tests/test_pregel.py
- tests/test_view.py
- Drop `3.10` from arangodb matrix
- Remove patch version from `3.11`
- First CI run with `latest` == `3.12`
- Doc updates
- Removal of 3.10 & 3.11 checks in the tests
> update arangodb matrix

- README.md
- arango/graph.py
- docs/graph.rst
- tests/test_graph.py
The `api/traversal` endpoint is no longer available starting with ArangoDB 3.12. This renders the `arango.graph.Graph.traverse()` unusable, causing the graph doctests to fail.
This PR makes the following adjustments:
- emit a warning if traverse() is used (should still work 3.11)
- skipping traversal test on newer ArangoDB versions (3.12+)
- change the graph traversal example, such that we no longer encourage people to use it
- changed readme traversal example
> Traversal API no longer available in 3.12

- arango/client.py
- arango/connection.py
- arango/exceptions.py
- tests/test_client.py
Updates the `ServerConnectionError` exception to inherit from `ArangoServerError ` instead of `ArangoClientError`, thereby giving us access to `error_code`, among other things.
Previously, the following code would just return the error message:
```py
from arango import ArangoClient
db = ArangoClient().db("bad_db", password="test", verify=True)
```
Whereas now we have access to the error code (i.e `1228`)
> fix: `ServerConnectionError`

- starter.sh
The selection works as follows
- "latest" => 3.12
- full version specified, using two dots, say "3.12.0" => 3.12
- otherwise, assuming we're using only one do, say "3.12" => 3.12
> Config file selection

- tests/test_collection.py
`test_collection.py::test_collection_management` now fails due to `arango.exceptions.CollectionCreateError: [HTTP 400][ERR 10] Value cannot be empty. on attribute distributeShardsLike`. This happens because the `shard_like` parameter is empty. Truth be told, that was never a valid configuration, but since 3.12 the validation got better and now we're actually throwing an exception.
This PR removes the empty value and adds proper testing for the `shard_like` parameter.
With that, all *cluster* tests should turn green.
> Fix collection test

- tests/test_transaction.py
We've had some issues with the transactions tests. After [digging a little deeper](https://github.com/arangodb/arangodb/pull/20874), I found out it was not the driver's fault.
This PR increases the transaction size limit to 1KB, so we should be safe from now on.
It should conclude the quest of making 3.12 builds green.
> Increasing size limit for transactions

- arango/collection.py
- tests/test_document.py
The current `has` method requests the full document to only check if it exists or not. It may be overkill for big documents.
This PR replaces it with a simple `HEAD` call allowing to know if the document exists or not.
:warning:  This PR will change the `error_code` returned. Since we don't have a body in the response, the `error_code` value will default to `status_code`.
If the only codes we should handle are the ones in the test, I could update the response object to set the appropriate `error_code` based on the status code.
> feat: Use HEAD HTTP method to check if a document exists

- .github/workflows/docs.yaml
- .readthedocs.yaml
- arango/request.py
- docs/conf.py
Removal of Sphinx context injection at build time has little effect for us.
Read [the blog post](https://about.readthedocs.com/blog/2024/07/addons-by-default/) from Read The Docs for more information.
However, this PR also updates the way docs are being build:
- We're using RTD build hook, which adds a new check for every PR (named docs/readthedocs.org:python-driver-for-arangodb). This comes with the park that we can now easily view the documentation build for every PR by clicking on details (a fake documentation page is generated).
- The docs action is not needed to build the documentation anymore. However, we'll keep it around for now in order to run the docs tests.
> RTD update

- arango/database.py
- arango/exceptions.py
- arango/executor.py
- pyproject.toml
- starter.sh
- tests/test_database.py
- tests/test_transaction.py
This PR integrates the following changes made in 3.12.1:
- new `skipFastLockRound` option for transactions (see [docs](https://docs.arangodb.com/3.13/develop/http-api/transactions/stream-transactions/#begin-a-stream-transaction_body_skipFastLockRound))
- new REST API endpoint HTTP DELETE `/_admin/log/level` to reset all log
levels to their startup values (see [docs](https://docs.arangodb.com/3.13/develop/http-api/monitoring/logs/#reset-the-server-log-levels))
Driver version 8.1.0 is prepared. Once this PR is merged, I'll proceed with the release.
> Integrate latest 3.12.1 changes

- arango/cluster.py
- arango/database.py
- arango/exceptions.py
- arango/formatter.py
- arango/request.py
- docs/admin.rst
- tests/test_cluster.py
- tests/test_database.py
* Add API GET `/_admin/cluster/vpackSortMigration/status` to query the status of the vpack sorting migration on dbservers, single servers and coordinators.
* The `_admin/log/level` endpoint has also been extended to with an optional
parameter `withAppenders`.
* There is also a migration API under GET `/_admin/cluster/vpackSortMigration/check` and PUT `/_admin/cluster/vpackSortMigration/migrate` to check for problematic indexes and - provided there are none - to migrate the instance to the new sorting order.
> Integrate latest 3.12.2 changes

- arango/database.py
Fixing the `users` parameter docstring for the `Database.create_database` function.
The [official documentation](https://docs.arangodb.com/stable/develop/http-api/databases/#create-a-database_body_users) states that only the root user will be added by default, if no users are specified.
The docstring is incorect because it claims that also the "current user" is included.
> Fix docstring

- arango/database.py
- tests/test_database.py
The license has to be a Base64-encoded string wrapped in double quotes.
See https://docs.arangodb.com/stable/develop/http-api/administration/#set-a-new-license
> License Parameter Docstring

- arango/utils.py
- tests/test_document.py
`db.collection().find(...)` was previously not working for nested fields
Happy to go with an alternative solution if there's an easier way
> update `collection.find` to support nested fields

- arango/aql.py
- arango/cursor.py
- arango/request.py
- tests/test_cursor.py
- Introduces support for setting the `profile` parameter in `db.aql.execute` to `2`, which returns additional `nodes` information via `cursor.statistics()`, along with the query execution plan (newly available via `cursor.plan()`)
- Warrants an `8.2.0` release
```
pip install git+https://github.com/arangodb/python-arango@ES-2276
```
```py
from arango import ArangoClient
db = ArangoClient().db()
cursor_a = db.aql.execute('FOR d IN doc SORT d._key RETURN d', profile=True)
cursor_b = db.aql.execute('FOR d IN doc SORT d._key RETURN d', profile=1)
cursor_c = db.aql.execute('FOR d IN doc SORT d._key RETURN d', profile=2)
assert cursor_a.statistics().keys() == cursor_b.statistics().keys()
assert cursor_a.profile().keys() == cursor_b.profile().keys()
assert cursor_a.plan() == cursor_b.plan() == …
```
> ES-2276 | support level 2 query profiling

- arango/cursor.py
Just a small documentation fix.
> The method does not raise CursorStateError

- .gitignore
- arango/collection.py
- arango/exceptions.py
- arango/utils.py
- docs/document.rst
- tests/test_document.py
add support for sorting by multiple fields in collection.find function
> add support for sort in collection.find function

- tests/test_cursor.py
ArangoDB 3.12.4 added a new key to the query execution plan. This PR makes sure the test won't fail anymore in the future, when coming across such DB updates.
> Keeping up with DB updates

- .circleci/config.yml
3.9 CI Failures are unrelated, and seem to also exist in the last commit to `main`.
Resolved in #361 though 👍
> attempt: 3.12 CI

- README.md
I forgot about the badge in my last PR.
I doesn't warrant a new release though. We no longer officially support 3.8, but the code works perfectly fine right now.
> Updating python version badge

- arango/job.py
- docs/async.rst
The documentation incorrectly states that the `status()` of an `AsyncJob` could have the value "cancelled". If you look at the implementation, the method may only return "pending" or "done". In all other cases, it raises an error.
Hence, we should not mention it.
> Removing "cancelled" response

- arango/client.py
- docs/certificates.rst
The certificates documentation explains in detail how to *switch off* cert verification, but doesn't mention anything about specifying a custom certification path.
> Updating docs

- arango/collection.py
- arango/utils.py
- tests/test_collection.py
While I was working on the async driver, I noticed a few things in the collections code:
1. The `truncate` method was missing some parameters: https://github.com/arangodb/python-arango/commit/ca09addfb0a0228c87a37e08e0287b3bc693378c
2. The `overwrite` parameter was unused by `update`: https://github.com/arangodb/python-arango/commit/d5ae65d5c6876a969d9c5813ad3fca26584cc815
3. Some docstrings have been adjusted: https://github.com/arangodb/python-arango/commit/f27348d857899b84dad60d19d520737df505d7e2 and https://github.com/arangodb/python-arango/commit/5bdc7a51c61b368bbc018f9064415469d91704c0 (batch execution is no longer supported)
> Collection Maintenance

- README.md
- arango/request.py
- docs/index.rst
I was thinking to do a new release anyway, and this is a good opportunity to mention the other driver.
> Mention async driver

- arango/collection.py
- tests/test_document.py
Noticed that `raise_on_document_error` exists on `StandardCollection.update_many`, but not on `insert_many` nor `delete_many`.
> new: `raise_on_document_error` for `insert_many` & `delete_many`

- arango/database.py
- tests/test_graph.py
This PR comes with two small changes:
1. The [sync parameter](https://docs.arangodb.com/stable/develop/http-api/graphs/named-graphs/#create-a-graph_query_waitForSync) is added to the `create_graph` method.
2. The `has_graph` method is optimized to fetch only the graph properties instead of a list containing all available graphs.
> Wait for sync upon graph creation

- arango/collection.py
- arango/exceptions.py
- arango/graph.py
- arango/request.py
- docs/graph.rst
- tests/test_graph.py
This PR does not modify much of the implementation, but adds or removes parameters to some of the graph-related functions.
- Vertex and Edge collections don't (actually never did) support the `silent` parameter. This could be confusing and it just makes type hinting more awkward because we have to return an `Union` instead of the actual type. See https://docs.arangodb.com/stable/develop/http-api/graphs/named-graphs/.
- Creating a vertex or edge collection has an additional `options` parameter which was not available in the driver.
- `replace_edge_definition` and `replace_vertex` were missing the `sync` parameter.
- The `edge_collections` method was missing. It corresponds to https://docs.arangodb.com/stable/develop/http-api/graphs/named-graphs/#list-edge-collections
- Added comments in …
> API Updates

- arango/connection.py
- starter.sh
- tests/test_database.py
Using `_db/{db_name}/_open/auth` is obsolete. We should simply use `/_open/auth` instead.
> Skip _db prefix on /_open/auth

- arango/database.py
- arango/exceptions.py
- tests/test_database.py
Add support for `GET /_db/{database-name}/_api/key-generators` introduced in 3.12
See https://docs.arangodb.com/stable/develop/http-api/collections/#get-the-available-key-generators
> Adding support for /key-generators

- arango/backup.py
- arango/collection.py
The collection load and unload methods have long been deprecate and are just NOPs since 3.9.
We should at least let the users know that these methods have no effect, and can safely be removed from their codebase.
See
- https://docs.arangodb.com/stable/develop/http-api/collections/#load-a-collection
- https://docs.arangodb.com/stable/develop/http-api/collections/#unload-a-collection
> Deprecate load/unload methods
